# ============================================================
#  hyprland.conf — Config principal FINAL
#  Hardware: Intel CPU | NVIDIA RTX 3070 | 32GB DDR5
#  Monitores: DP-1 (4K@60) izquierda | DP-2 (2K@360) derecha
# ============================================================

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf

# ── Autostart ─────────────────────────────────────────────
exec-once = awww-daemon
exec-once = sleep 2 && awww img /home/trafalgar/.config/hypr/wallpapers/arch-cap.jpg
exec-once = waybar
exec-once = mako
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'catppuccin-mocha-mauve-standard+default'
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# ── General ───────────────────────────────────────────────
general {
  gaps_in           = 5
  gaps_out          = 10
  border_size       = 2
  col.active_border   = rgba(cba6f7ff) rgba(89b4faff) 45deg
  col.inactive_border = rgba(6c7086aa)
  layout            = dwindle
  resize_on_border  = true
}

decoration {
  rounding = 10
  blur {
    enabled           = true
    size              = 5
    passes            = 2
    vibrancy          = 0.2
    new_optimizations = true
  }
}

animations {
  enabled = true
  bezier  = overshot,  0.05, 0.9, 0.1, 1.05
  bezier  = smoothOut, 0.5,  0,   0.99, 0.99

  animation = windows,    1, 5,  overshot,  slide
  animation = windowsOut, 1, 4,  smoothOut, popin 80%
  animation = fade,       1, 7,  default
  animation = workspaces, 1, 5,  overshot
  animation = border,     1, 10, default
}

input {
  kb_layout    = es
  follow_mouse = 1
  sensitivity  = 0
}

dwindle {
  preserve_split = true
  smart_split    = true
  force_split    = 2
}

misc {
  force_default_wallpaper  = 0
  disable_hyprland_logo    = true
  disable_splash_rendering = true
  mouse_move_enables_dpms  = true
  key_press_enables_dpms   = true
  vrr = 2
}

xwayland {
  force_zero_scaling = true   # apps legacy nítidas en 4K
}
