# ============================================================
#  hyprland.conf — Config principal
#  Hardware: Intel CPU | NVIDIA RTX 3070 | 32GB DDR5
#  Monitores: DP-1 (4K@60) izquierda | DP-2 (2K@360) derecha
# ============================================================

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/workspaces.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/theme.conf        # ← tema activo

# ── Autostart ─────────────────────────────────────────────
exec-once = awww-daemon
exec-once = sleep 2 && awww img /home/trafalgar/.config/hypr/wallpapers/arch-cap.jpg
exec-once = waybar
exec-once = mako
exec-once = hypridle
exec-once = wl-paste --watch cliphist store
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# ── Prioridad ─────────────────────────────────────────────
env = STEAM_RUNTIME_PREFER_HOST_LIBRARIES,1

# ── Input ─────────────────────────────────────────────────
input {
  kb_layout    = es
  follow_mouse = 1
  sensitivity  = 0
}

# ── Layout ────────────────────────────────────────────────
dwindle {
  preserve_split = true
  smart_split    = true
  force_split    = 2
}

# ── Misc ──────────────────────────────────────────────────
misc {
  force_default_wallpaper  = 0
  disable_hyprland_logo    = true
  disable_splash_rendering = true
  mouse_move_enables_dpms  = true
  key_press_enables_dpms   = true
  vrr                      = 2
}

# ── XWayland ──────────────────────────────────────────────
xwayland {
  force_zero_scaling = true
}
