# ============================================================
#  hypridle.conf
# ============================================================

general {
  lock_cmd         = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd  = hyprctl dispatch dpms on
}

# 5 min → atenuar brillo
listener {
  timeout    = 300
  on-timeout = brightnessctl -s set 30%
  on-resume  = brightnessctl -r
}

# 8 min → bloquear pantalla
listener {
  timeout    = 480
  on-timeout = loginctl lock-session
}

# 10 min → apagar monitores
listener {
  timeout    = 600
  on-timeout = hyprctl dispatch dpms off
  on-resume  = hyprctl dispatch dpms on
}

# 30 min → suspender (comenta si no quieres suspensión automática)
listener {
  timeout    = 1800
  on-timeout = systemctl suspend
}
