font_family      Terminess Nerd Font
bold_font        Terminess Nerd Font Bold
italic_font      Terminess Nerd Font Italic
bold_italic_font Terminess Nerd Font Bold Italic
font_size        13.0

cursor_shape              block
cursor_blink_interval     0.5
cursor_stop_blinking_after 15.0
cursor                    #9b59d0

scrollback_lines          10000
window_padding_width      12
hide_window_decorations   yes
background_opacity        1.0
tab_bar_edge              bottom
tab_bar_style             separator
tab_separator             " │ "
tab_title_template        " {title} "
active_tab_font_style     bold
enable_audio_bell         no

foreground              #c0c0c0
background              #000000
selection_foreground    #000000
selection_background    #9b59d0
cursor_text_color       #000000
url_color               #00d4ff
active_border_color     #9b59d0
inactive_border_color   #1a1a1a
active_tab_foreground   #000000
active_tab_background   #9b59d0
inactive_tab_foreground #555555
inactive_tab_background #000000
tab_bar_background      #000000
color0  #0a0a0a
color8  #1a1a1a
color1  #ff3355
color9  #ff5577
color2  #00cc88
color10 #33ddaa
color3  #ffaa00
color11 #ffcc44
color4  #00d4ff
color12 #44ddff
color5  #9b59d0
color13 #bb77ee
color6  #00cc88
color14 #33ddaa
color7  #c0c0c0
color15 #e0e0e0

map ctrl+shift+c  copy_to_clipboard
map ctrl+shift+v  paste_from_clipboard
map ctrl+shift+t  new_tab_with_cwd
map ctrl+shift+w  close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left  previous_tab
map ctrl+equal    change_font_size all +1.0
map ctrl+minus    change_font_size all -1.0
