[theme]
name        = Neon OLED
author      = trafalgar
version     = 1.0
description = TUI-style OLED — system24, magenta + púrpura

[gtk]
gtk-theme   = neon-dark
icon-theme  = Papirus-Dark
font        = Iosevka 11
cursor      = Bibata-Modern-Classic
cursor-size = 24

[wallpaper]
file        = guts-neon-iconic-5120x2880-21415.png
transition  = fade
