# ── Catppuccin Mocha — colores Hyprland ──────────────────
general {
  gaps_in          = 5
  gaps_out         = 10
  border_size      = 2
  col.active_border   = rgba(cba6f7ff) rgba(89b4faff) 45deg
  col.inactive_border = rgba(6c7086aa)
  layout           = dwindle
  resize_on_border = true
}

decoration {
  rounding = 10
  blur {
    enabled           = true
    size              = 5
    passes            = 2
    vibrancy          = 0.2
    new_optimizations = true
  }
}

animations {
  enabled = true
  bezier  = overshot,  0.05, 0.9, 0.1, 1.05
  bezier  = smoothOut, 0.5,  0,   0.99, 0.99
  animation = windows,    1, 5,  overshot,  slide
  animation = windowsOut, 1, 4,  smoothOut, popin 80%
  animation = fade,       1, 7,  default
  animation = workspaces, 1, 5,  overshot
  animation = border,     1, 10, default
}
