[theme]
name        = Catppuccin Mocha
author      = trafalgar
version     = 1.0
description = Catppuccin Mocha — tema suave y colorido

[gtk]
gtk-theme   = catppuccin-mocha-mauve-standard+default
icon-theme  = Fluent-dark
font        = Noto Sans 11
cursor      = Bibata-Modern-Classic
cursor-size = 24

[wallpaper]
file        = arch-cap.jpg
transition  = fade
